name: Generate contribution-snake

# give write access so GITHUB_TOKEN can push
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    # confirm this job can write too
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # needed for full history
          persist-credentials: true  # keep GITHUB_TOKEN in git config

      - name: Generate snake SVG & GIF
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
            output/github-contribution-grid-snake.svg?palette=github-light

      - name: Commit & push to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
          directory: output
